#!/usr/bin/env bash

DOTFILES="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"


# Tmux
rm -rf $HOME/.tmux.conf
ln -sf $DOTFILES/tmux/tmux.conf $HOME/.tmux.conf

# Scripts
mkdir -p $HOME/.local/bin

rm -rf $HOME/.local/bin/t
rm -rf $HOME/.local/bin/deliver

ln -sf $DOTFILES/scripts/t $HOME/.local/bin/t
ln -sf $DOTFILES/scripts/deliver $HOME/.local/bin/deliver
