#!/usr/bin/env bash

DOTFILES="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

# test

# Tmux
rm -rf $HOME/.tmux.conf
ln -sf $DOTFILES/tmux/tmux.conf $HOME/.tmux.conf

# Scripts
mkdir -p $HOME/.local/bin

rm -rf $HOME/.local/bin/t
rm -rf $HOME/.local/bin/deliver

ln -sf $DOTFILES/scripts/t $HOME/.local/bin/t
ln -sf $DOTFILES/scripts/deliver $HOME/.local/bin/deliver

# Tmux
rm -rf $HOME/.config/nvim
ln -sf $DOTFILES/nvim $HOME/.config/nvim


rm -rf $HOME/.config/phpactor
ln -sf $DOTFILES/nvim $HOME/.config/phpactor
